name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Update dependencies
          run: |
               sudo apt update -y &&\
               sudo apt-get -y install libnss3 libnspr4\
                    libatk1.0-0\
                    libatk-bridge2.0-0\
                    libdrm2\
                    libxkbcommon0\
                    libatspi2.0-0\
                    libxcomposite1\
                    libxdamage1\
                    libxfixes3\
                    libxrandr2\
                    libgbm1\
                    libasound2
        - name: Install
          run: npm install
        - name: Bundle application
          run: npm run package
        - name: Check chrome version
          run: google-chrome --version
        - name: Test
          run: |
            npm run wdio wdio.github.conf.js
